# Generated by Django 2.2.5 on 2021-01-24 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20210121_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='bedroooms',
            new_name='bedrooms',
        ),
    ]
